version: '3'
services:
  dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    env_file:
      - ./.env
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    command: ["npm", "run", "test"]
